=== kardos24/ARSOPracticas/Practicas 1/ejercicio1-2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT calificaciones (calificacion+, diligencia*)>
<!ELEMENT calificacion EMPTY >
<!ELEMENT diligencia EMPTY>

<!ATTLIST calificaciones 
	asignatura CDATA #REQUIRED
	convocatoria (febrero|junio|julio) #REQUIRED
	curso CDATA #IMPLIED
> 
<!ATTLIST calificacion
	nif CDATA #REQUIRED
	nombre CDATA #IMPLIED
	nota NMTOKEN #REQUIRED
> 
<!ATTLIST diligencia
	nif CDATA #REQUIRED
	nombre CDATA #IMPLIED
	nota NMTOKEN #REQUIRED
	fecha CDATA #REQUIRED
	extraordinaria (si|no) "no"
>

=== kardos24/ARSOPracticas/Practicas 1/ejercicio1-2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE calificaciones SYSTEM "ejercicio1-2.dtd">


<calificaciones asignatura="Software" convocatoria="febrero" curso="3">
	<calificacion nif="489999G" nombre="Manuel" nota="10"/>
	<calificacion nif="410010G" nota="5"/>
	<calificacion nif="566755G" nombre="Carlos" nota="7"/>
	<diligencia nif="897666H" nombre="Javier" nota="8" fecha="20-2-17" extraordinaria="si"/>
	<diligencia nif="892423H" nota="8" fecha="20-2-17" />
	<diligencia nif="214366H" nota="8" fecha="20-2-17" extraordinaria="si"/>
	<diligencia nif="000006H" nombre="San Apostol" nota="8" fecha="20-2-17" />

</calificaciones>
